version: 2.1

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py27:
    docker:
      - image: circleci/python:2.7

commands:
  run_unittest:
    steps:
      - checkout
      - run:
          name: install tox
          command: pip install --user tox
      - run:
          name: Run Flake8
          command: /home/circleci/.local/bin/tox -e flake8
jobs:

  unittests_py27:
    executor: py27
    steps:
      - run_unittest


workflows:
  version: 2
  tests:
    jobs:
      - unittests_py27

  nightly:
    triggers:
    - schedule:
        cron: "0 3 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - unittests_py27
