version: 2.1

orbs:
  node: cloudify/public-unittest-orb@volatile

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

workflows:
  version: 2.1
  tests:
    jobs:
      - node/unittests_job

  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * 0,2,4,6"
          filters:
            branches:
              only:
                - master
    jobs:
      - node/unittests_job
